
const foods = [
  {
    "name": "اسپرسو دبل",
    "MainPrice": "96000",
    "sizes": null,
    "category": "اسپرسو",
    "categoryId": 25527,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/gfvfau.png",
    "description": "صد عربیکا",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "کافه لته",
    "MainPrice": "134000",
    "sizes": null,
    "category": "اسپرسو",
    "categoryId": 25527,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/rulcrc.png",
    "description": " (۲۵۰ میلی شیر و دو شات اسپرسو )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "کاپوچینو",
    "MainPrice": "124000",
    "sizes": null,
    "category": "اسپرسو",
    "categoryId": 25527,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/djetfb.png",
    "description": "( قهوه + شیر ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "آمریکانو",
    "MainPrice": "96000",
    "sizes": null,
    "category": "اسپرسو",
    "categoryId": 25527,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( قهوه + آب جوش ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "کارامل ماکیاتو",
    "MainPrice": "170000",
    "sizes": null,
    "category": "اسپرسو",
    "categoryId": 25527,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "موکا",
    "MainPrice": "169000",
    "sizes": null,
    "category": "اسپرسو",
    "categoryId": 25527,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/tkskjn.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "فدرال",
    "MainPrice": "210000",
    "sizes": null,
    "category": "اسپرسو",
    "categoryId": 25527,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/tgroaq.png",
    "description": "( قهوه + شیر عسل + خامه + شیر ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "سیر و استیک",
    "MainPrice": "575000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/hzcfux.png",
    "description": "( راسته گوساله+پنیر پارمسان+سس سیر ویژه+پنیر پیتزا طبیعی )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "رست بیف",
    "MainPrice": "519000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": " ( راسته گوساله رست شده+قارچ+سس سیر ویژه+پنیر پیتزا طبیعی )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "مرغ و پستو",
    "MainPrice": "555000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( مرغ گریل+سس سیر+ریحان ایتالیایی+پسته+قارچ )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "سزار",
    "MainPrice": "395000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( شینسل مرغ گریل شده + گوجه + زیتون + سس سزار + پنیر پیتزا طبیعی ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "شکاری و بیکن",
    "MainPrice": "475000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/yaueht.png",
    "description": "( بیکن+سوسیس شکاری+پنیرلبنه+سس گوجه+پنیر پیتزا طبیعی )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "پپرونی",
    "MainPrice": "385000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": " ( پپرونی+هالوپینو+سس گوجه+پنیر پیتزا طبیعی )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "نوستالژی",
    "MainPrice": "395000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "ژامون مرغ ۹۰٪+قارچ+فلفل دلمه ای+پنیر پیتزا طبیعی",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "نان و  پنیرو گردو",
    "MainPrice": "255000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "وجیتاله",
    "MainPrice": "275000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/kytjym.png",
    "description": "( سبزیجات تازه فصل+سس ترافل+پنیر پیتزا طبیعی)",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "مارگریتا",
    "MainPrice": "225000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/acpqmc.png",
    "description": "( ریحان + پنیر پارمسان + سس گوجه + پنیر پیتزا طبیعی )  ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "نان سیر",
    "MainPrice": "225000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( سس سیر ویژه + پنیر پیتزا طبیعی ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "چهارپنیر",
    "MainPrice": "295000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( پنیر لبنه+پنیر پارمسان+پنیر گودا+پنیر پیتزا )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "گوشت و‌ پیاز",
    "MainPrice": "479000",
    "sizes": null,
    "category": "پیتزا",
    "categoryId": 25875,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( گوشت چرخ کرده+پیاز+قارچ+سس ناپولی+پنیر پیتزا طبیعی )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "آفوگاتو",
    "MainPrice": "155000",
    "sizes": null,
    "category": "قهوه سرد",
    "categoryId": 25532,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( بستنی + قهوه ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "فراپاچینو",
    "MainPrice": "175000",
    "sizes": null,
    "category": "قهوه سرد",
    "categoryId": 25532,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( قهوه + بستنی + پنیر خامه ای + کارامل )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "لایم کافی",
    "MainPrice": "175000",
    "sizes": null,
    "category": "قهوه سرد",
    "categoryId": 25532,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/owwllj.png",
    "description": "( قهوه + سودا + سیروپ + شکر + آب لیمو )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "برگر کلاسیک",
    "MainPrice": "265000",
    "sizes": null,
    "category": "برگر دست ساز",
    "categoryId": 25541,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( برگر 100% دست ساز + پیاز کاراملی + کاهو + گوجه + خیارشور + سیب زمینی ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "چیز برگر",
    "MainPrice": "285000",
    "sizes": null,
    "category": "برگر دست ساز",
    "categoryId": 25541,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( کلاسیک + گودا )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "اسپشیال برگر",
    "MainPrice": "335000",
    "sizes": null,
    "category": "برگر دست ساز",
    "categoryId": 25541,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( کلاسیک + بیکن + گودا )  ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "ماشروم برگر",
    "MainPrice": "355000",
    "sizes": null,
    "category": "برگر دست ساز",
    "categoryId": 25541,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( اسپشیال + سس قارچ )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "فرانسه",
    "MainPrice": "82000",
    "sizes": null,
    "category": "قهوه های دمی",
    "categoryId": 25531,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "کمکس",
    "MainPrice": "0",
    "sizes": null,
    "category": "قهوه های دمی",
    "categoryId": 25531,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "وی شصت",
    "MainPrice": "0",
    "sizes": null,
    "category": "قهوه های دمی",
    "categoryId": 25531,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "ایروپرس",
    "MainPrice": "0",
    "sizes": null,
    "category": "قهوه های دمی",
    "categoryId": 25531,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "ترک",
    "MainPrice": "0",
    "sizes": null,
    "category": "قهوه های دمی",
    "categoryId": 25531,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/akehuw.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "بیف استراگانوف",
    "MainPrice": "285000",
    "sizes": null,
    "category": "ساندویچ",
    "categoryId": 25872,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "مرغ و اسفناج",
    "MainPrice": "265000",
    "sizes": null,
    "category": "ساندویچ",
    "categoryId": 25872,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "چیکن استراگانوف",
    "MainPrice": "285000",
    "sizes": null,
    "category": "ساندویچ",
    "categoryId": 25872,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( شینسل گریل شده + سس قارچ + پنیر گودا ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "چیکن هالوپینو",
    "MainPrice": "275000",
    "sizes": null,
    "category": "ساندویچ",
    "categoryId": 25872,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( شینسل گریل شده + ژامبون مرغ + سس هالوپینو + پنیر پیتزا ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "هات داگ وبیکن",
    "MainPrice": "275000",
    "sizes": null,
    "category": "ساندویچ",
    "categoryId": 25872,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": " (۱ عدد هات داگ ۷۰٪گوشت+بیکن+سس گوجه+پنیر پیتزا طبیعی )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "قهوه اریایی",
    "MainPrice": "56000",
    "sizes": null,
    "category": "نوشیدنی گرم",
    "categoryId": 25530,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( ترکیب ۱۶ تا گیاه دارویی+قهوه )\nخواص: تقویت اعصاب و انرژی بخش",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "چای کرک",
    "MainPrice": "135000",
    "sizes": null,
    "category": "نوشیدنی گرم",
    "categoryId": 25530,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "چای ماسالا",
    "MainPrice": "135000",
    "sizes": null,
    "category": "نوشیدنی گرم",
    "categoryId": 25530,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/ankjir.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "هات چاکلت",
    "MainPrice": "135000",
    "sizes": null,
    "category": "نوشیدنی گرم",
    "categoryId": 25530,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "چای",
    "MainPrice": "55000",
    "sizes": null,
    "category": "نوشیدنی گرم",
    "categoryId": 25530,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "دمنوش",
    "MainPrice": "85000",
    "sizes": null,
    "category": "نوشیدنی گرم",
    "categoryId": 25530,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "شیرکاکائو",
    "MainPrice": "95000",
    "sizes": null,
    "category": "نوشیدنی گرم",
    "categoryId": 25530,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "استیک گوشت",
    "MainPrice": "825000",
    "sizes": null,
    "category": "غذای اصلی",
    "categoryId": 25871,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/htlifn.png",
    "description": "( راسته گوساله + سبزیجات گریل شده + سس قارچ ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "استیک مرغ",
    "MainPrice": "425000",
    "sizes": null,
    "category": "غذای اصلی",
    "categoryId": 25871,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/kvsggm.png",
    "description": "(شنسیل مرغ + سیب زمینی + دورچین ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "لازانیا کلاسیک",
    "MainPrice": "385000",
    "sizes": null,
    "category": "غذای اصلی",
    "categoryId": 25871,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "لازانیا چیکن ناپولی",
    "MainPrice": "375000",
    "sizes": null,
    "category": "غذای اصلی",
    "categoryId": 25871,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "لازانیا اسفناج و خامه",
    "MainPrice": "325000",
    "sizes": null,
    "category": "غذای اصلی",
    "categoryId": 25871,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "پاستا آلفردو",
    "MainPrice": "375000",
    "sizes": null,
    "category": "غذای اصلی",
    "categoryId": 25871,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/xgdldu.png",
    "description": "( پنه ریگاته + شیسل مرغ + قارچ + سس آلفردو ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "چیپس و پنیر",
    "MainPrice": "535000",
    "sizes": null,
    "category": "غذای اصلی",
    "categoryId": 25871,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/rqaetn.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "فیگو چیلی",
    "MainPrice": "157000",
    "sizes": null,
    "category": "ماکتیل",
    "categoryId": 25533,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/ivnrtm.png",
    "description": "( پشن فروت + انبه + زنجبیل + فلفل ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "گرانچ",
    "MainPrice": "157000",
    "sizes": null,
    "category": "ماکتیل",
    "categoryId": 25533,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/vxgiod.png",
    "description": "( انار + آلوورا + پرتقال + لیمو ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "ویولت پانچ",
    "MainPrice": "157000",
    "sizes": null,
    "category": "ماکتیل",
    "categoryId": 25533,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/yxoboi.png",
    "description": "( انار + آلوورا + گل گاو زبان + نسترن + بهار نارنج + پنیرک ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "سینامون گریپس",
    "MainPrice": "157000",
    "sizes": null,
    "category": "ماکتیل",
    "categoryId": 25533,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/tsloww.png",
    "description": "( انگور + دارچین + آلبالو + پرتقال + لیمو ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "موهیتو",
    "MainPrice": "135000",
    "sizes": null,
    "category": "ماکتیل",
    "categoryId": 25533,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/inpobn.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "لیموناد",
    "MainPrice": "125000",
    "sizes": null,
    "category": "ماکتیل",
    "categoryId": 25533,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/emfghk.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "سالاد سزار",
    "MainPrice": "425000",
    "sizes": null,
    "category": "سالاد و پیش غذا",
    "categoryId": 25543,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/cvkusx.png",
    "description": "( کاهو + فیله سوخاری / شینسل + سزار + گوجه گیلاسی + نان سیر + زیتون )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "سالاد ایتالیایی",
    "MainPrice": "445000",
    "sizes": null,
    "category": "سالاد و پیش غذا",
    "categoryId": 25543,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/dusjhr.png",
    "description": "( کاهو + شینسل مرغ + سس ایتالیایی + گردو + گوجه گیلاسی ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "سیب زمینی کلاسیک",
    "MainPrice": "125000",
    "sizes": null,
    "category": "سالاد و پیش غذا",
    "categoryId": 25543,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "سیب زمینی مشتی",
    "MainPrice": "395000",
    "sizes": null,
    "category": "سالاد و پیش غذا",
    "categoryId": 25543,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "سیب زمینی با سس قارچ",
    "MainPrice": "245000",
    "sizes": null,
    "category": "سالاد و پیش غذا",
    "categoryId": 25543,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "کوکو بری",
    "MainPrice": "195000",
    "sizes": null,
    "category": "اسموتی",
    "categoryId": 25535,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/fqnzel.png",
    "description": "( پیناکولادا + خامه + توت فرنگی + نارگیل ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "اسکای بلو",
    "MainPrice": "195000",
    "sizes": null,
    "category": "اسموتی",
    "categoryId": 25535,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/icskou.png",
    "description": "( بلوکاراسئو + آناناس + هل + بستنی )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "استوایی",
    "MainPrice": "235000",
    "sizes": null,
    "category": "اسموتی",
    "categoryId": 25535,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( انبه + موز + پشن فروت+  آناناس ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "ردبری",
    "MainPrice": "215000",
    "sizes": null,
    "category": "اسموتی",
    "categoryId": 25535,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/yrotuh.png",
    "description": "( آلبالو + توت فرنگی + کرن بری + لیمو ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "گرین دریم",
    "MainPrice": "215000",
    "sizes": null,
    "category": "اسموتی",
    "categoryId": 25535,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/bidirz.png",
    "description": "( سیب + عسل + اسفناج + آلوورا )  ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "انگلیسی",
    "MainPrice": "295000",
    "sizes": null,
    "category": "صبحانه",
    "categoryId": 25873,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/yvchbq.png",
    "description": "( هات داگ + تست بیکن + سیب زمینی + لوبیا+ قارچ )  ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "بولراملت",
    "MainPrice": "275000",
    "sizes": null,
    "category": "صبحانه",
    "categoryId": 25873,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/vxecxe.png",
    "description": "( گوشت راسته گوساله + تخم مرغ + قارچ + نخود فرنگی + پیاز کاراملی ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "میکس مک",
    "MainPrice": "255000",
    "sizes": null,
    "category": "صبحانه",
    "categoryId": 25873,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/nvzyog.png",
    "description": "( 2 عدد نان مک + سس اسفناج + سس پنیر گردو + تخم مرغ + پنیر گودا ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "پنکیک",
    "MainPrice": "175000",
    "sizes": null,
    "category": "صبحانه",
    "categoryId": 25873,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "شیرعسل دارچین\nنوتلا\nمیوه",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "فرانسوی",
    "MainPrice": "235000",
    "sizes": null,
    "category": "صبحانه",
    "categoryId": 25873,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/klyhhg.png",
    "description": "( قارچ + هالوپینو + بیکن + تخم مرغ ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "کسادیا اگز",
    "MainPrice": "235000",
    "sizes": null,
    "category": "صبحانه",
    "categoryId": 25873,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( میکس سبزیجات + تخم مرغ + پنیر پیتزا + نان پیتا )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "اگ رول ساسیج",
    "MainPrice": "235000",
    "sizes": null,
    "category": "صبحانه",
    "categoryId": 25873,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/ydsyjp.png",
    "description": "( هات داگ + سس قارچ + تخم مرغ )  ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "املت قارچ اسفناج",
    "MainPrice": "195000",
    "sizes": null,
    "category": "صبحانه",
    "categoryId": 25873,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( سس اسفناج + پنیر پیتزا + تخم مرغ ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "املت مخصوص",
    "MainPrice": "195000",
    "sizes": null,
    "category": "صبحانه",
    "categoryId": 25873,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/ijkfce.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "املت",
    "MainPrice": "145000",
    "sizes": null,
    "category": "صبحانه",
    "categoryId": 25873,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/iicwxf.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "بشقاب ایرانی",
    "MainPrice": "160000",
    "sizes": null,
    "category": "صبحانه",
    "categoryId": 25873,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": " ( پنیر+عسل+خامه+کره )",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "نوتلا",
    "MainPrice": "225000",
    "sizes": null,
    "category": "شیک",
    "categoryId": 25876,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( نوتلا + بستنی وانیل ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "تیرامیسو",
    "MainPrice": "195000",
    "sizes": null,
    "category": "شیک",
    "categoryId": 25876,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( قهوه + کارامل + بیسکوییت + بستنی وانیل + پنیر خامه ای ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "ماکیاتو",
    "MainPrice": "195000",
    "sizes": null,
    "category": "شیک",
    "categoryId": 25876,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( قهوه + کارامل + بستنی ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "لیمو انبه",
    "MainPrice": "189000",
    "sizes": null,
    "category": "شیک",
    "categoryId": 25876,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( انبه + لیمو + بستنی ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "بیسکوییت",
    "MainPrice": "179000",
    "sizes": null,
    "category": "شیک",
    "categoryId": 25876,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( کرم بیسکوییت + بستنی وانیل ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "کلاسیک",
    "MainPrice": "179000",
    "sizes": null,
    "category": "شیک",
    "categoryId": 25876,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "( موز + انبه + توت فرنگی + شکلات + بستنی ) ",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "چیز کیک تیرامیسو",
    "MainPrice": "115000",
    "sizes": null,
    "category": "کیک",
    "categoryId": 25877,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "شکلات دست ساز",
    "MainPrice": "15000",
    "sizes": null,
    "category": "کیک",
    "categoryId": 25877,
    "image": "https://api.rhinomenu.com/food/images/4hxpx22h/nyipen.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "کروسان",
    "MainPrice": "97",
    "sizes": null,
    "category": "کیک",
    "categoryId": 25877,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "کوکی",
    "MainPrice": "27",
    "sizes": null,
    "category": "کیک",
    "categoryId": 25877,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "Kerno",
    "MainPrice": "275000",
    "sizes": null,
    "category": "قلیان",
    "categoryId": 26740,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "کوکا",
    "MainPrice": "43000",
    "sizes": null,
    "category": "‌‌نوشیدنی‌ها",
    "categoryId": 27295,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "زیرو",
    "MainPrice": "43000",
    "sizes": null,
    "category": "‌‌نوشیدنی‌ها",
    "categoryId": 27295,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "فانتا",
    "MainPrice": "43000",
    "sizes": null,
    "category": "‌‌نوشیدنی‌ها",
    "categoryId": 27295,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "اسپرایت",
    "MainPrice": "43000",
    "sizes": null,
    "category": "‌‌نوشیدنی‌ها",
    "categoryId": 27295,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "دوغ آبعلی",
    "MainPrice": "27000",
    "sizes": null,
    "category": "‌‌نوشیدنی‌ها",
    "categoryId": 27295,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "دلستر استوایی",
    "MainPrice": "43000",
    "sizes": null,
    "category": "‌‌نوشیدنی‌ها",
    "categoryId": 27295,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  },
  {
    "name": "دلستر هلو",
    "MainPrice": "43000",
    "sizes": null,
    "category": "‌‌نوشیدنی‌ها",
    "categoryId": 27295,
    "image": "https://api.rhinomenu.com/members/images/4hxpx22h/girpey.png",
    "description": "",
    "videoUrl": "",
    "status": 1
  }
];

export { foods };